### ISSUE TITLE
failing on first use. lack of documentation to get started

### ISSUE THREAD

**Issue by laurencefass** [signalpoint/jdrupal-drupal-example#1]
installed this example and the main module for first use. im seeing the following error report when loading the default page. this repeats on each page load.

```
Type | php
-- | --
Tuesday, October 24, 2017 - 17:28
user1
http://jscript840.vs/user/1?_format=json
http://jscript840.vs/jdrupal
Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException: Not acceptable format: json in Drupal\Core\EventSubscriber\RenderArrayNonHtmlSubscriber->onRespond() (line 30 of /home/jscript840/drupal-8.4.0/core/lib/Drupal/Core/EventSubscriber/RenderArrayNonHtmlSubscriber.php).
Error
192.168.1.200
```

**Comment by laurencefass** [comment]
what is the sitepath in app.js meant to be? no documentation....

**Comment by signalpoint** [comment]
@laurencefass  See step number 5 here: http://jdrupal.tylerfrankenstein.com/8/docs/Hello_World

As for your error, that's a Drupal error, sounds like you need to enable JSON formats on your Drupal site's rest configuration.
